name: Gosec
on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - main
      - kparkinson/SEC-2664/add-gotsec-github-action

permissions:
  id-token: write
  contents: read

jobs:
  Gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: launchdarkly/gha-ld-gosec@v1
        with:
          aws-assume-role: ${{ secrets.ORG_SECURITY_GHA_ROLE_ARN }}
